apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: tls-secret2
spec:
  secretName: tls-secret2
  dnsNames:
  - smarthotel220-web.westeurope.cloudapp.azure.com
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - smarthotel220-web.westeurope.cloudapp.azure.com
  issuerRef:
    name: letsencrypt-staging2
    kind: ClusterIssuer