apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging2
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    # https://acme-staging.api.letsencrypt.org/directory
    # https://acme-staging-v02.api.letsencrypt.org/directory
    # https://acme-v01.api.letsencrypt.org/directory
    email: prosto100vip@gmail.com
    privateKeySecretRef:
      name: letsencrypt-staging2
    http01: {}